
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int Mientras = 7;
  public static final int ParentDer = 3;
  public static final int ParentIzq = 2;
  public static final int CorchDer = 5;
  public static final int EOF = 0;
  public static final int Variables = 6;
  public static final int CorchIzq = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ParentIzq",
  "ParentDer",
  "CorchIzq",
  "CorchDer",
  "Variables",
  "Mientras"
  };
}

